### ISSUE TITLE
Does not work with new Clang versions

### ISSUE THREAD

**Issue by retr0devops** [GANGE666/xVMP#6]
Tested using Clang 15, Clang 16

Got EXC_BAD_ACCESS on govmtranslator::handle_callinst
Using lldb I think the problem is that gv_data_seg is nullptr at the moment of program compiling

**Comment by TUGOhost** [comment]
I think you need Clang 8

**Comment by retr0devops** [comment]
> I think you need Clang 8

I updated this project to Clang 14. With Clang 14 all works fine.
